### ISSUE TITLE
Toy Restful interface

### ISSUE THREAD

**Issue by mortonjt** [biocore/empress#10]
We'll want this in order to facilitate communication between the model / view / controller.
For starters, let's just have simple get / post commands made.

Eventually, we'll want to have the following enabled.

- [ ] Post node/edge metadata (model)
- [ ] Get node/edge metadata (viewer)

We'll want to have this protocol prototyped in
- [ ] Python Flask
- [ ] Javascript node.js

This [python tutorial](https://blog.miguelgrinberg.com/post/designing-a-restful-api-with-python-and-flask) could be useful.
This [node.js tutorial](https://www.codementor.io/olatundegaruba/nodejs-restful-apis-in-10-minutes-q0sgsfhbd) could be useful.

**Comment by htoo97** [comment]
For the post/get requests, isn't it:

- [ ] GET node/edge metadata (model)

- [ ]  POST node/edge metadata (view)

...since we're trying to GET the dataframes that the model computed and POST them to the viewer?
