### ISSUE TITLE
Create metadata tests (to address NaN issue)

### ISSUE THREAD

**Issue by kwcantrell** [biocore/empress#128]
to address #126

**Comment by gibsramen** [comment]
To clarify - what should we be testing for here? If I'm understanding correctly, we would like to verify that if a sample/feature metadata file has NaN(s) that things work as normal?

**Comment by ElDeveloper** [comment]
@gibsramen, yes that's what we would like to check.

**Comment by ElDeveloper** [comment]
This is relevant because of the serialization to JSON.

**Comment by fedarko** [comment]
I think probably the most painless way to test this (as far as I can tell) would be adding a test to `tests/python/test_core.py` which verifies that the `Empress._to_dict()` method's output looks ok. Could probably reuse a lot of the data / logic from `test_to_dict()`.

**Comment by gibsramen** [comment]
Cool, yeah @fedarko that was my plan as well.

**Comment by ElDeveloper** [comment]
One more thing to check would be calling `make_empress` in a test, and ensure this doesn't raise any errors when there are NaNs. This is because the Template calls `tojson`.

**Comment by ElDeveloper** [comment]
Closed by @gibsramen in #238.
