### ISSUE TITLE
Possible to set a negative line width

### ISSUE THREAD

**Issue by fedarko** [biocore/empress#135]
I assume this isn't intended (if it's actually a feature feel free to close this :) -- assuming it isn't, should be possible to add in `min="1"` or something to the corresponding `<input>` element.

Edit: should also add JS that validates that the new branch thickness is within a range of acceptable values, as a failsafe. Relates to #144.

Screenshot of a -10 width below (I admit it does look kind of cool, though) --

![issue](https://user-images.githubusercontent.com/4177727/73655426-e4490d00-4642-11ea-98c6-c07d1d58a47b.png)

**Comment by ElDeveloper** [comment]
Related to #214

**Comment by ElDeveloper** [comment]
Would be good to centralize and unify the setting of line widths.

**Comment by fedarko** [comment]
I think it might work well to handle #144 alongside these changes for the next release, also.
