### ISSUE TITLE
"Classic QIIME Colors" are incorrectly assigned

### ISSUE THREAD

**Issue by fedarko** [biocore/empress#137]
The hex codes [here](https://github.com/biocore/empress/blob/0f4c98d348ade522474408692551859f99eda10e/empress/support_files/js/colorer.js#L34-L59) match up with Emperor as far as I can tell, but when you use this color scheme in Empress the colors look pretty different -- some of the colors are shades of grayish brown which (esp. when line widths are all 1) are pretty hard to distinguish from uncolored branches.

![issue1](https://user-images.githubusercontent.com/4177727/73657880-098c4a00-4648-11ea-9cf5-27b92c5f4229.png)

Ideally it would be good to have the colors be consistent with Emperor, since I imagine this is probably the "default" color scheme people using Empress will try first.

Also, if possible, it would be good for colors to be consistent across different amounts of fields -- e.g. when you select `barcode-sequence` as the field to color by instead of `body-site`, the first few "Classic QIIME" colors after red are different. For discrete color schemes, at least, this behavior seems counterintuitive to me (although I can totally understand how it'd be useful for quantitative colorschemes like viridis). Looks like the origin of this behavior is [in this function](https://github.com/biocore/empress/blob/0f4c98d348ade522474408692551859f99eda10e/empress/support_files/js/empress.js#L323-L338)?

![issue2](https://user-images.githubusercontent.com/4177727/73657792-e1045000-4647-11ea-83eb-4707416a015f.png)

**Comment by fedarko** [comment]
As a small update, I did some digging today and it looks like the root of the problem is that discrete color schemes are being treated the way you'd expect quantitative color schemes to be treated. On the default QIIME color scheme, this results in the somewhat odd light green and beige colors shown above -- as far as I can tell these are the results from chroma.js trying to "interpolate" stuff from the QIIME color scheme.

For discrete color schemes, my understanding of the "expected behavior" when assigning colors to `n` categories (at least this is the way Emperor does it?) is that you just select the first `n` colors from the color scheme (looping around when you have more categories than color scheme entries), rather than treating the color map as a range and attempting to interpolate from this range (as is done here).

Long story short, the following modified version of `empress._assignColor()` resolves the problem when the default color scheme (`Classic QIIME Colors`) is selected, although there's some extra work to be done in generalizing this fix to arbitrary color schemes.

```js
Empress.prototype._assignColor = function(items, color, forWebGl) {
    // create color brewer
    // NEW: the "max" number of the Colorer's domain, 23, is set
    // this way because there are 24 colors in the "Classic QIIME Colors"
    // color scheme. When generalizing this to arbitrary color schemes we
    // should determine how many colors are in the color scheme (or better
    // yet, delegate this sorta stuff to chroma.js).
    var colorer = new Colorer(color, 0, 23);
    var colorFunction = forWebGl ? "getColorRGB" : "getColorHex";

    var cm = {};
    for (var i = 0; i < items.length; i++) {
        var item = items[i];
        cm[item] = {
            // NEW: rather than computing a block size that we use to space out
            // categories (items), just assign colors by picking from the start
            // of the color scheme.
            color: colorer[colorFunction](i % 23)
        };
    }
    return cm;
};
```

This yields the following for the moving pictures tree -- distinguishing between categories is much easier with these colors:

![mpixgood](https://user-images.githubusercontent.com/4177727/77217219-03f6a080-6ade-11ea-9893-9053827e310c.png)

In the future it may be worth splitting the coloring code up into two separate functions, one for discrete and one for quantitative scales. Not sure if that's something that was available in the old version of Empress that hasn't been ported over yet.

IMO this issue (or at least getting the QIIME colors working) will be important to address at some point, since having nice defaults is always good.

**Comment by ElDeveloper** [comment]
@fedarko, thanks so much for looking into this. You are right in how this should be handled - do you think this is close to get a PR in place?

You are right about how this is handled in Emperor.

-------------

For reference here's a few links to Emperor's source code:

Here's the list of colors and classifications:
https://github.com/biocore/emperor/blob/master/emperor/support_files/js/color-view-controller.js#L580

Here's the discrete color selection:
https://github.com/biocore/emperor/blob/master/emperor/support_files/js/color-view-controller.js#L350

Here's the continuous color selection:
https://github.com/biocore/emperor/blob/master/emperor/support_files/js/color-view-controller.js#L398

**Comment by fedarko** [comment]
@ElDeveloper, just to check -- would you like for me to work on getting both discrete and continuous colorschemes working as part of a PR for this issue, or should I just focus on discrete for now?
