### ISSUE TITLE
Supporting running Empress outside of QIIME 2?

### ISSUE THREAD

**Issue by fedarko** [biocore/empress#140]
As far as I'm aware, the current branch of Empress only supports visualizations through QIIME 2 (using `qiime empress plot`). It might be nice to support generating visualizations (i.e. just a folder containing the HTML, JS, etc. that would be in the QZV file anyway) outside of QIIME 2 -- this would open up the user base to people who are unfamiliar with / don't necessarily want to install QIIME 2.

(**edit:** As a nice side effect, this'll also make it a lot easier to write unit tests for `_plot.py`.)

Doing this should be doable without much extra work -- [most of the internals of `plot()` in `_plot.py`](https://github.com/biocore/empress/blob/master/empress/_plot.py#L33-L101) seem independent of QIIME 2, so I think the easiest way to do this would just be moving this code to a separate Python file and then making separate Python functions (one for Q2 stuff and one for standalone stuff) that each call this shared code.

As an example of this in practice this is the general paradigm Qurro uses ([standalone plotting code](https://github.com/biocore/qurro/blob/master/qurro/scripts/_plot.py), [q2 plotting code](https://github.com/biocore/qurro/blob/master/qurro/q2/_visualizers.py)), and it's worked reasonably well for that at least.

**Comment by ElDeveloper** [comment]
I would prioritize first having a Python object to run Empress. This will facilitate writing other interfaces and refactoring _plot.py. That of course after some of the other issues currently open 😆 🚀

**Comment by fedarko** [comment]
One of my commit messages #154 contained a paragraph saying something like "When we resolve #140, ..." and apparently github interpreted that as a request to close this issue... we're not done with this quite yet :sweat_smile:
