### ISSUE TITLE
Add a marker to show where the root is for rooted trees

### ISSUE THREAD

**Issue by ElDeveloper** [biocore/empress#141]
We should include and document a marker for where the root of the tree is located. This should be added after some of the layout changes make it into the repo.

**Comment by fedarko** [comment]
May be worth considering the "hide non-sample features" option, and how that interacts with this. As part of the #139 fixes, we will be able to safely assume that the root / a descendant of it is always present in at least one sample, right?

**Comment by fedarko** [comment]
Updates on this, for reference: #160 added a special marker for the root but it wasn't selectable\*, and as of b1ce0be0d01dbe39b70960a4705b55a8874acfcb (for #169) the root node is now both marked and selectable. So when the feature metadata branch is merged in, I think this can be closed?

\* (Also I'm a little ashamed to admit that I just spent like 15 minutes digging through the code and I still don't know where this marker is actually being set.)
