### ISSUE TITLE
Split side panel HTML template and JS into separate files

### ISSUE THREAD

**Issue by fedarko** [biocore/empress#150]
From @kwcantrell in https://github.com/biocore/empress/pull/145#discussion_r401166063:

> I think we should split side-panel.html into two separate files (i.e. tabs). One for sample coloring and one for "global" properties such layouts and default background/branch color. Same for SidePanel.js. Split SidePanel.js into SampleColorPanel.js and GlobalPropertiesPanel.js.

**Comment by kwcantrell** [comment]
I am going to close this issue. Feel free to reopen this but I think our current method of handling side-panel is sufficient.
