### ISSUE TITLE
Figure out what's up with internal nodes being colored but children not colored during animation

### ISSUE THREAD

**Issue by fedarko** [biocore/empress#152]
![image](https://user-images.githubusercontent.com/4177727/78597139-d1e57e00-7801-11ea-8526-1cdeb8ba17c1.png)

May be an artifact of weird input data or of animation/coloring stuff.

**Comment by fedarko** [comment]
I think I've identified the cause of this. As far as I can tell, this has to do with `Empress._projectObservations()`:

https://github.com/biocore/empress/blob/6e4bbd3cc53a79494ebe05b8db174086f02169a4/empress/support_files/js/empress.js#L629-L649

For reference, my understanding of how this function works is that it accepts an Object  (`obs`) mapping categories (e.g. `body_site`) to nodes in the tree present within these categories. This then goes through the tree in a post-order traversal, expanding `obs` by defining each node N's parent P to be present in the same group that N is in, if any. This will obviously not create unique assignments for nodes that are present in multiple categories / have descendants present in multiple categories, so there's a call to `util.keepUniqueKeys()` at the end that filters each category to just those nodes unique to it.

**The problem with this approach** is that it does not, as far as I can tell, consider "not in any of the categories" to itself be a category. So if you have a simple tree like

```
      + --- B
      |
A --- + 
      |
      + --- C
```

where B is in category "1" and C isn't in any categories, then A will still be considered by `_projectObservations` to be unique to category "1":

```
      + === B
      #
A === + 
      |
      + --- C
```

I guess the way to move forward with this bug is first acknowledging -- this actually is a bug, right? I can see how you might make an argument for this being "desired" behavior in some cases (my personal opinion is that this is a bug, but I might be biased because I just spent a while tracking this down :).

If we agree that this is a bug, then I'm not sure how it would be best to fix this. We could maintain a separate data structure during the postorder traversal of "nodes that aren't in any category" and use that analogously to an entry in `obs`, I guess? Not sure.

In any case, we should definitely add tests for this function so this problem doesn't happen again. My personal vote is for porting it over to the `BPTree` module, which unlike `empress.js` already has tests set up (so adding more tests shouldn't be too much work ... hopefully.)

**Comment by kwcantrell** [comment]
Good catch @fedarko! You are correct, _projectObservations does not take into account tips that do not belong to a unique category. 

I also agree that this is a bug because if a tip belongs to multiple categories then it would fall under "not in any of the categories" so it may be miss leading if we keep the current behavior. Here is my proposed solution, before the main loop of _projectObservations, we can create an object that maps the direct parents of the tips in obs to a count of how many of its children are in obs. Then, we can iterate throughi obs and only keep the tips that have all of their siblings are in obs.

**Comment by ElDeveloper** [comment]
This makes sense, make sure to differentiate between tips that are not 
represented by any sample and tips that are represented by multiple samples. 
Tips that are not represented by any sample should for the most part just be 
ignored from this propagation. And in the other case your suggestion makes 
sense.

**Comment by kwcantrell** [comment]
@ElDeveloper so you think we should still propagate the color up the tree if an internal node has children that do not belong to any samples (i.e. we will still get the current behavior for tips that are not in the feature table) and don't propagate the color when an internal node has children that belong to multiple samples? I think this option is better. However, we should distinguish uncolored tip that belong to multiple samples vs tips that aren't in the feature table. So, I think we should add all tips that belong to multiple categories to a "non-unique" category and assign them a color.

**Comment by ElDeveloper** [comment]
Yes, exactly. I agree with your conclusion, those should be distinguished 
using different colors.
