### ISSUE TITLE
Make animation / normal line widths consistent

### ISSUE THREAD

**Issue by fedarko** [biocore/empress#153]
It seems like there are some interaction bugs that can arise when the "sample coloring" and "animation" line widths differ. I also suspect that these are thickening lines in different ways; see [here](https://github.com/biocore/empress/issues/144#issuecomment-606949844).

Related to #144.

**Comment by fedarko** [comment]
This seems like it's more severe than I remembered for animation -- see below. Not sure if there were changes recently that impacted this.

![image](https://user-images.githubusercontent.com/4177727/84724635-80621980-af3d-11ea-8da2-03eab1251aa5.png)

**Comment by kwcantrell** [comment]
I believe this was addressed in  #180. @fedarko feel free to open this issue up again if that did not address the issue.
