### ISSUE TITLE
Make Empress.Tree subclass bp.Tree rather than skbio.TreeNode

### ISSUE THREAD

**Issue by fedarko** [biocore/empress#155]
@ElDeveloper and @antgonza have both brought up ([1](https://github.com/biocore/empress/pull/145#discussion_r399712873), [2](https://github.com/biocore/empress/pull/154#discussion_r405500630)) that the current workflow for creating an Empress Tree in `empress/_plot.py` is a bit inefficient, since the input newick file goes through the following steps:

1. Read using `bp.parse_newick()`
2. Converted to a scikit-bio `TreeNode` using `bp.to_skbio_treenode()`
3. Converted to an Empress `Tree` using `empress.tree.Tree.from_tree()`

If we could cut out the scikit-bio step and just rely on the `bp` implementation, this would likely speed things up.

That being said, IMO the more worrying bottlenecks are on the JavaScript side of things -- optimizing that side will likely be more of a challenge than optimizing the Python side of things, so I'd argue that that is where we should focus efforts on optimization for the time being. (But obviously making either side faster is always nicer :)

Related issues: #151

(I haven't mentioned it here but there are [similar concerns with how sample metadata is treated](https://github.com/biocore/empress/pull/154#discussion_r405502286), since it goes from `qiime2.Metadata` to `pd.DataFrame` to `dict`.)

**Comment by ElDeveloper** [comment]
Should be addressed by #213

**Comment by fedarko** [comment]
I think there'll still be some extra work we could do on this issue post #213 -- the `skbio.TreeNode` representation of the tree is still used for a few things in the python code, and ripping these out / replacing them with uses of the bp tree would probably save us some time. (Might be worth making a new issue, though...)
