### ISSUE TITLE
Storing JS BIOM data more efficiently

### ISSUE THREAD

**Issue by fedarko** [biocore/empress#158]
The JS BIOM table representation is structured as follows:

`{sample1: [feature1, feature2, feature3, ...], sample2: [feature3, feature4, ...], ...}`

...where `sample1`, `feature1`, etc. are the sample / feature IDs.

This approach inherently results in feature IDs being repeated multiple times, since they'll be listed for every sample they're in (a perfectly dense table with `N` samples will result in a JS representation where every feature ID is listed `N` times). If the input dataset isn't that huge and/or if the feature IDs are small strings this isn't a big deal, but when feature IDs are listed as sequences they represent (anywhere from a ~90 to ~500+ character string) this can inflate the `empress.html` (and the QZV) file sizes, because these long strings are listed multiple times.

A way to get around this problem would be finagling things so that each feature is assigned a unique numeric ID (starting at, say, 1, then going up to `number of features`), and the actual feature ID is stored only once somewhere in the data passed to Empress' JS code (maybe with the feature metadata, when we add that back in). This way, referencing a feature in the BIOM table won't require nearly as much space in the `empress.html` file.

Another way to get around this problem (this might be easier) would just be storing the transpose of the table --

`{feature1: [sample1, sample3, ...], feature2: [sample1, sample5, sample6. ...], ...}`

... since sample IDs are usually much shorter than feature IDs :) This is the approach Qurro currently takes.

Anyway, not urgent or anything, but this would probably help with the issue brought up in #74.

**Edit**: Per discussion with @wasade, the redbiom data model may be a useful example of how to implement this.

**Comment by ElDeveloper** [comment]
Using numbers instead of sequences would be a good way to cope with this.

Thanks!

Yoshiki

**Comment by wasade** [comment]
Basically something like:

```javascript
sample_lookup = {'sample_name': <unique_integer>, ...}
sample_lookup_inverse = {<unique_integer>: 'sample_name'}
feature_lookup = {'feature_name': <unique_integer>, ...}
feature_lookup_inverse = {<unique_integer>: 'feature_name'}
sample_counts = {sample_idx: {'counts': [count, count, count, ...], 'features': [feature_idx, feature_idx, ...]}
```

...where "counts" and "features" are in index order

**Comment by fedarko** [comment]
@wasade Thanks so much! As I'm implementing this, there are two changes that I think might simplify things with this approach. Wanted to post them here to check that I'm not falling into any pitfalls that you may have already dealt with for redbiom.

1. I think it might be possible to simplify the lookup storage by converting `sample_lookup_inverse` and `feature_lookup_inverse` to arrays:

```
s_ids = ['s1', 's2', 's3', ...]
f_ids = ['f1', 'f2', 'f3', ...]
```

Each sample or feature's unique ID would just be its 0-based position in the sample or feature array (`0` -> `s1`, etc.). For the sake of things like feature-ID searching, Empress would still need to maintain a non-inverse feature lookup object mapping feature names to their `f_ids` index -- I guess it's either that or sort the feature IDs in that array in alphabetical order from the start, and then use e.g. binary searching on `f_ids` to locate a feature's index in the JS. (But that sounds like overkill.)

2. For the `sample_counts` internals, do you see a problem with consolidating `counts` and `features` into the same object? Something like

```
sample_counts = {sample_idx: {feature_idx: ct, feature_idx: ct, ...}, sample_idx: {...}, ...}
```

... Where entries in each `sample_idx` object where `ct` is 0 are just omitted. I *think* this should save some space, but I'm not 100% confident of that.

**Comment by ElDeveloper** [comment]
For the sake of completeness, this is roughly the same approach that's followed in Emperor's [`Plottable` class](http://biocore.github.io/emperor/build/jsdoc/Plottable.html) (see the idx property).

**Comment by fedarko** [comment]
quick update on how this is going -- [this branch](https://github.com/fedarko/empress/tree/smol-biom) of my fork compresses the table, sample, and feature metadata mostly as described above before storing them in the HTML.

Although the branch is untested (and broken, since I haven't gotten the JS set up to work with the compressed data yet), the compressed data does save a lot of space: for the HMP dataset Kalen shared with me, the `empress.html` file from the uncompressed QZV is **47 MB**, and the `empress.html` file from the compressed QZV is **26 MB**. There are definitely further ways we could bring this number down, also (e.g. minifying the HTML).

**Comment by ElDeveloper** [comment]
This is great to hear @fedarko. Have you noticed any performance improvements on the UI side of things? Are loading times faster?

**Comment by fedarko** [comment]
Sorry, I'm still working on getting the JS to use the compressed data, but I'll update here when I have that working :)

**Comment by ElDeveloper** [comment]
👍 no worries - exciting times!
