### ISSUE TITLE
Removing redundant tree_data from the HTML / JS

### ISSUE THREAD

**Issue by fedarko** [biocore/empress#163]
Not urgent, but there's code in `_plot.py` that does the following:

https://github.com/biocore/empress/blob/6e4bbd3cc53a79494ebe05b8db174086f02169a4/empress/_plot.py#L82-L89

Since `color` and `sampVal` are the same for every node, it should be possible to omit these from the JSON. For trees with lots of nodes this would cut down on QZV size (and probably memory usage in the visualization) by a decent amount.

Even though attributes like `color` are changed dynamically in the visualization, we should be able to infer that -- for example -- a missing `color` for some node means that that node has the default color, aka `[0.75, 0.75, 0.75]` or whatever the default color is set to (#143).

**Comment by ElDeveloper** [comment]
See if possible to reduce as many of the attributes saved here.
