### ISSUE TITLE
files names in tutorial 

### ISSUE THREAD

**Issue by antgonza** [biocore/empress#171]
If a user follows: https://github.com/biocore/empress#example-using-empress-in-qiime-2; the `sample_metadata.tsv` downloaded file is actually named: `Moving\ Pictures\ sample-metadata\ \(QIIME\ 2\ 2019.10\)\ -\ sample-metadata.tsv`.

**Comment by fedarko** [comment]
Oh, dang. That's annoying -- thanks for the catch!

From what I can tell, the most recently released Q2 moving pictures tutorial [deals with this](https://docs.qiime2.org/2020.2/tutorials/moving-pictures/#sample-metadata) by asking the user to download and save the file as `sample-metadata.tsv`, or providing wget/curl commands that name the file properly.

My preference here is limiting the tutorial's complexity as much as possible, so I vote for us changing the sample metadata download link to point to the [copy of the sample metadata file included in this repository](https://raw.githubusercontent.com/biocore/empress/master/docs/moving-pictures/sample_metadata.tsv). This link opens up a new tab (in my browser at least), and hitting ctrl-S in this window defaults to saving the file as just `sample_metadata.tsv`, as expected.

**Comment by antgonza** [comment]
Sounds good to me but I think then we should a step in the travis build that runs those commands, just in case something changes in future either in QIIME 2 or empress ...

**Comment by fedarko** [comment]
Would modifying the README's view/download links to _all_ point to these files' [location in the Empress repo](https://github.com/biocore/empress/tree/master/docs/moving-pictures) be an acceptable solution? There's already a [basic integration test](https://github.com/biocore/empress/blob/master/tests/python/test_integration.py) that uses these QZA / metadata files, so we should be able to safely assume that these files are available.

**Comment by ElDeveloper** [comment]
Testing the tutorial would be great, but I think that will be easier if/when the plugin is integrated with QIIME2. Either of the solutions proposed here work, so as long as the tutorial works 👍
