### ISSUE TITLE
Add vertical overflow handling (e.g. a scrollbar) to the side panel

### ISSUE THREAD

**Issue by fedarko** [biocore/empress#173]
When you open up all of the sub-panels, the animation panel goes off the screen:

![image](https://user-images.githubusercontent.com/4177727/84635069-8dccc480-aea7-11ea-8523-0652ccd3c062.png)

(There are scrollbars on the screen due to #168, but these only "scroll" the legend and not the side panel.)

As we add more functionality to Empress, this will become more of a problem.

**Comment by sjanssen2** [comment]
I just wanted to report this issue, which occurs on my Linux machine both with Firefox and Chrome.
