### ISSUE TITLE
Test that sample presence information is computed properly

### ISSUE THREAD

**Issue by fedarko** [biocore/empress#187]
Currently, it "double-counts" samples across duplicate-name nodes, which causes too-large numbers.

Options include (from discussion with @kwcantrell and @ElDeveloper):

- Just show stats for the single node selected, even if its name is duplicated
- Don't show anything for this node (there should be a warning in the selected node menu anyway; can expand this warning to say this is why stats aren't shown)

See [comment here](https://github.com/biocore/empress/pull/183/files#r442407897).

**Comment by fedarko** [comment]
For reference, as of v0.2.0 this shouldn't be a problem -- if the user searches for a node with an ambiguous name, then the resulting dialog doesn't show sample presence info for the matching nodes. In all other cases where the node isn't ambiguous (the user clicked on a node, or the user searched for a node with an unambiguous name), a table of sample presence information for just that node is shown in the dialog.

Possible cases:

1. user clicks on tip
2. user clicks on int. node with unique name
3. user clicks on int. node with ambiguous name
4. user searches for tip
5. user searches for int. node with unique name
6. user searches for int. node with ambiguous name (**only case where the table should be omitted**, because the node is unclear)

Although things seem to be working now, it would be good to test that things work as expected. Ideally we'd test all of the above cases, but we should at least cover 1, 3, 5, and 6.

**Comment by ElDeveloper** [comment]
Addressed in #274
