### ISSUE TITLE
Export to SVG

### ISSUE THREAD

**Issue by ElDeveloper** [biocore/empress#202]
This should in principle be possible using the data from the different data buffers. 

https://developer.mozilla.org/en-US/docs/Web/SVG/Element

**Comment by sjanssen2** [comment]
I love the export to SVG function in Emperor and use it for many publication to give the figures the final touch and I am a passionate user of Inkscape, thus I would love to take a look into this enhancement. I hope I can carve out the necessary time to code up something soon (remote teaching is eating up a lot of my bandwidth). Is this blocking any other development?

**Comment by kwcantrell** [comment]
@sjanssen2 if you want to work on this feature that would be awesome! I don't believe anything is currently being block by this feature. For reference,  [Here](https://github.com/biocore/empress/milestone/3) is a list of the current features we are working on.

**Comment by ElDeveloper** [comment]
@sjanssen2, let us know if you need any help with this!

**Comment by ElDeveloper** [comment]
Addressed in #218
