### ISSUE TITLE
Put node name / ID in a scrollbar once it gets too long

### ISSUE THREAD

**Issue by fedarko** [biocore/empress#205]
This is mainly a problem for when features are exact sequences (e.g. sOTUs of lengths >= 150), since this can cause funky formatting of the node selection menu like:

![image](https://user-images.githubusercontent.com/4177727/85614502-cc811e00-b60f-11ea-977f-04b83cb773af.png)

It may be best to wrap the `ID: TACTATATACACAGT...` header in a `<div>` with a max width and `overflow-x: scroll;` so that the menu doesn't look off.

Happy to take this on, since it will probably end up tying into #181.

**Comment by ElDeveloper** [comment]
That makes sense. Another alternative would be truncating the string to a set number of characters and additionally having a button to copy the full string to the clipboard.
