### ISSUE TITLE
Show full tree

### ISSUE THREAD

**Issue by sjanssen2** [biocore/empress#208]
In my case, I am using a phylogeny resulting from fragment insertion of Deblur features in the Greengenes 13.8 reference tree. It should have some ~230k tips. I figure the shown tree "only" renders the tree sheared to those tips that are contained in the provided feature-table.

However, it would be useful to "see" which parts of the big reference phylogeny is covered by actual reads of my samples. Thus my question: is it possible to show the "full" tree in Empress?

#179 would than be even more important.

**Comment by kwcantrell** [comment]
@sjanssen2 you should be able to view the whole tree using filter_unobserved_features_from_phylogeny=True.

Currently, Empress sets filter_unobserved_features_from_phylogeny=False as default so that it is fast to initialize an Empress plot.

**Comment by kwcantrell** [comment]
I am going to go ahead and close this issue. @sjanssen2 feel free to open this issue up if the above suggestion didn't address your question.

**Comment by sjanssen2** [comment]
My fault. I haven't seen this option. It is really cool - although a bit slow ;-)
