### ISSUE TITLE
User action documentation

### ISSUE THREAD

**Issue by sjanssen2** [biocore/empress#210]
I feel a bit lost when interacting with Empress. From the code, I figure it should somehow be possible to collapse sub-trees, but how do I accomplish that? Is there already some end user documentation that I am missing?

**Comment by ElDeveloper** [comment]
Good point, I think having some documentation about the available features would be great.

**Comment by ElDeveloper** [comment]
Assigned to @mestaki 👍 thanks!

**Comment by ElDeveloper** [comment]
@mestaki, friendly ping - it would be very helpful if you could submit a PR for his by the end of the day or tomorrow morning. 👍
