### ISSUE TITLE
Set root marker to a non-circle shape, and allow recoloring based on root node's color

### ISSUE THREAD

**Issue by fedarko** [biocore/empress#211]
1. Justification for the "shape" thing is described in detail in the thread starting [here](https://github.com/biocore/empress/issues/143#issuecomment-649089045). Making this its own issue so I don't forget about that :)

2. Regarding the "recoloring" thing: this is due to a very minor issue that I doubt most users will run into. When the root node has a unique color (i.e. when coloring by feature metadata using both internal node / tip metadata, and the root has a unique value for the selected feature metadata field), this color is included in the legend as expected:

![image](https://user-images.githubusercontent.com/4177727/85769439-d74eb800-b6ce-11ea-9ef6-019d9847d7f7.png)

However, the only layout that actually draws anything besides the marker for the root node is the rectangular layout. In the circular and unrooted layout, no lines for the root node are drawn, and therefore the entry in the legend for the root node's unique color goes unused in the tree. This could confuse users:

![image](https://user-images.githubusercontent.com/4177727/85769603-ff3e1b80-b6ce-11ea-9728-2817ad79d35e.png)

A way around _this_ issue would be no longer coloring the root marker black, but instead allowing its color to change based on its node color (ensuring that the root node's unique color in the legend is actually reflected somewhere in the tree).

**Comment by ElDeveloper** [comment]
> A way around this issue would be no longer coloring the root marker black, but instead allowing its color to change based on its node color (ensuring that the root node's unique color in the legend is actually reflected somewhere in the tree).

Interested in what others think but this sounds like a good option.

**Comment by kwcantrell** [comment]
I agree, we should change the root marker to a special shape and allow its color to change based on its node color. This would allow the user to still visually see the root as well as resolve the legend issue.
