### ISSUE TITLE
Build artifacts when a new PR is posted

### ISSUE THREAD

**Issue by ElDeveloper** [biocore/empress#236]
This can potentially be done using GitHub services, or if needed the small server that we use to host documentation.

- Pull down the branch
- Run make docs
- Post a link on the PR to the live artifacts.

**Comment by antgonza** [comment]
Reading online, it seems like this is what we will need to do: https://github.community/t/possible-to-commit-files-after-workflow-runs/17824/2

Now, do we have a preference on the commit user details and the token to use?

**Comment by ElDeveloper** [comment]
@antgonza that's super cool. Do you think we could adapt this to show the built QZVs once a new PR is opened?

As for the credentials, I think we can re-use https://github.com/emperor-helper, but really it could be whatever account.

**Comment by antgonza** [comment]
I _think_ so, would you mind sending me an email with the details for that account, I'll be happy to tests ...
