### ISSUE TITLE
Tree fails to load when using rarefied table from moving pictures tutorial

### ISSUE THREAD

**Issue by ElDeveloper** [biocore/empress#241]
If you replace `docs/moving-pictures/table.qza` for [this table from the tutorial](https://docs.qiime2.org/2020.6/data/tutorials/moving-pictures/core-metrics-results/rarefied_table.qza) everything works fine except the visualization fails to load with this error:

```
require-2.1.22.min.js:19 TypeError: Cannot read property 'x2' of undefined
    at Empress.getX (empress.js:217)
    at Empress.getCoords (empress.js:446)
    at Empress.drawTree (empress.js:210)
    at Empress.centerLayoutAvgPoint (empress.js:1174)
    at Empress.initialize (empress.js:203)
    at empress.html:312
    at Object.execCb (require-2.1.22.min.js:30)
    at ea.check (require-2.1.22.min.js:18)
    at ea.<anonymous> (require-2.1.22.min.js:23)
    at require-2.1.22.min.js:8
```

Just in case, [here's the broken artifact](https://view.qiime2.org/?src=https%3A%2F%2Fwww.dropbox.com%2Fs%2Fci5ncj8kl1kjktv%2Fbroken-empress-tree.qzv%3Fdl%3D0).

**Comment by antgonza** [comment]
I have a theory, does this happen if you pass the `--p-no-filter-unobserved-features-from-phylogeny`?

**Comment by fedarko** [comment]
While working on #240 I wound into the same sort of error ("Cannot read property 'x2' of undefined"). In that case, the problem was caused by a node being set to `undefined` by accident, due to passing an invalid key to `empress._treeData` (since in JS an out-of-bounds index on an object is just `undefined`).

Not sure exactly what's going on...

**Comment by antgonza** [comment]
I have seen this before and I think is because the expansion of the tree is not working properly. I'll take a look ... a quick fix is to not do shifting in the tree and pass unknown to the size.
