### ISSUE TITLE
Convert coordinate objects into arrays

### ISSUE THREAD

**Issue by ElDeveloper** [biocore/empress#258]
The idea is to change this:

`{'name': 'a', 'x2': 1, 'xc0': 2, 'xc1': 3, 'xr': 4, 'y2': 5, 'yc0': 6, 'yc1': 7, 'yr': 8}`

To this:

`['a', 1, 2, 3, 4, 5, 6, 7, 8]`

This should save python from writing all the repeated key data, and save JavaScript from parsing all of that. We would just need to load the data in a container once it's parsed in JavaScript. Originally brought up in #231.

**Comment by fedarko** [comment]
Closed by #301!
