### ISSUE TITLE
Certain QUnit Puppeteer tests failing

### ISSUE THREAD

**Issue by gibsramen** [biocore/empress#265]
In setting up for Empress development I was unable to successfully call `make jstest` as 28 tests would fail. Most seem to be of the format `Cannot read property <x> of null`. Note that opening the `index.html` page shows all tests passing so there is some discrepancy on my end.

During conversation with @fedarko (#262) we tried to debug for a while to no avail. Attaching a file with the full suite of failures.

[js_test_error.txt](https://github.com/biocore/empress/files/4932341/js_test_error.txt)

**Comment by kwcantrell** [comment]
@gibsramen I can help you look into this a bit later today. But it looks like all the errors are a result of canvas not being initialized. The index.html file creates the following:

  
  <div id="tree-container" class="{{ emperor_classes }}">
    <div class="container {{ emperor_classes }}">
      <canvas class="tree-surface" id="tree-surface">
          Your browser does not support HTML5
      </canvas>
    </div>
  </div>

So I am wondering if somehow your puppeteer environment is failing to create it. Canvas requires WebGl so it might be that you are using an older version of headless-chromium that doesn't support WebGl.

**Comment by kwcantrell** [comment]
@gibsramen I've done some additional testing and I can't seem to recreate your issue so I think you might be using an outdated version of either nodejs, npm, or puppeteer/chromium. 

If you aren't using nodejs for another project, you start from a clean slate by first deleting nodejs/npm.  Then follow these steps:

1) Install NVM (which is sorta like conda but instead manages nodejs version).
`curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash`

2) close terminal/reopen terminal

3) Install nodejs (which will also install npm)
`nvm install node`

4) Install packages for empress testing
`npm install -g qunit-puppeteer jshint prettier`

**Comment by kwcantrell** [comment]
@gibsramen after our conversation today, I am going to go ahead and close this issue. Feel free to open it back up again if the solution did not work.
