### ISSUE TITLE
Support ignoring branch lengths during layout

### ISSUE THREAD

**Issue by fedarko** [biocore/empress#271]
Suggestion from @gibsramen last week.

This (along with #170) would be a nice use case of doing layouts in the JavaScript code (#213), since that'd allow users to compare the same tree with and without branch lengths being used quickly.

For reference, here are some comparison screenshots on the moving pictures dataset (coloring by phylum):

#### With branch lengths

![image](https://user-images.githubusercontent.com/4177727/87998886-10036680-caae-11ea-9cc3-a061460ca090.png)

#### Uniform branch length of 1

![image](https://user-images.githubusercontent.com/4177727/87998900-1b569200-caae-11ea-9264-34d73afd0ee2.png)

#### With branch lengths
![image](https://user-images.githubusercontent.com/4177727/87998940-3f19d800-caae-11ea-8072-df071872c901.png)

#### Uniform branch length of 1
![image](https://user-images.githubusercontent.com/4177727/87998925-32957f80-caae-11ea-8470-d32d2bb9652e.png)

#### With branch lengths
![image](https://user-images.githubusercontent.com/4177727/87998959-4f31b780-caae-11ea-8705-2ee5551a17b3.png)

#### Uniform branch length of 1
![image](https://user-images.githubusercontent.com/4177727/87998983-5eb10080-caae-11ea-9b55-aaa6244121aa.png)

**Comment by kwcantrell** [comment]
In addition, by moving the layout calculation to javascript, it would help simplify the python code. In particular #155

Also, I believe that we would also get a slight performance boost since layouts require looping through the tree which python is not very efficient at.
