### ISSUE TITLE
Support showing multiple toast messages at once

### ISSUE THREAD

**Issue by fedarko** [biocore/empress#286]
Technically a bug, but IMO more of a feature request.

Some of the barplot code involves showing errors to the user if certain settings are invalid for a barplot layer (e.g. the user tries to do numeric scaling with a non-numeric field, or the user sets the maximum bar length to have a value less than the minimum bar length). I figured it'd be nice to show these errors to the user via `util.toastMsg()`.

However, there are two problems I've run into with this approach:

1. Only one error message can be shown at a time, since there is just a single `#toast` HTML element being used.

2. The use of `setTimeout()` to re-hide the `#toast` element means that, if multiple error messages are triggered within a short timespan, not all of them will be shown for an equal time -- the first error message's timeout will cause "later" error messages to be hidden early. (This is the same sort of problem as what causes #197.) See the end of this post for a rough "log" and GIF of what this sort of situation looks like.

It would be nice to develop the toast functionality a bit so that multiple messages can be shown simultaneously without bonking into each other. This _could_ involve making `util.toastMsg()` more complex, but I think __probably the easiest course of action for everyone would just be using an established third-party library for showing toasts__: one of the following should be more than sufficient --

- [Bootstrap's toast functionality](https://getbootstrap.com/docs/4.3/components/toasts/)
- [toastr](https://codeseven.github.io/toastr/demo.html)
- [jQuery toast plugin](https://kamranahmed.info/toast)

Thanks!

### Appendix: what timeouts bonking into each other looks like
```
0 seconds in: user triggers error A, a toast message appears with a duration of 5000 ms (aka 5 seconds)
1 seconds in: toast A error message is visible
2 seconds in: toast A error message is visible
3 seconds in: user triggers error B, a toast message appears with a duration of 5000 ms
4 seconds in: toast B error message is visible
5 seconds in: error A's timeout activates and the toast is hidden, even though error message B was only shown for ~2 seconds
```

![toast](https://user-images.githubusercontent.com/4177727/88960269-1e911100-d258-11ea-8a9b-e6703fc0752a.gif)

**Comment by ElDeveloper** [comment]
Thanks for tagging this @fedarko, as you point out it would probably be good to defer to a 3rd party library.
