### ISSUE TITLE
Coloring root nodes of collapsed clades?

### ISSUE THREAD

**Issue by fedarko** [biocore/empress#321]
We talked a bit about this a few days ago, so I'm making a note of it here for future reference. I think it might make sense to color in the root nodes of collapsed clades, since they would already be colored that way if collapsing were not done. If opinions are split on which option (color root vs. don't color root) looks better / is more useful, we could make this an option in "Tree Properties" as well.

![image](https://user-images.githubusercontent.com/4177727/89845914-a7e7f380-db34-11ea-9ecf-ba5132ccbaf1.png)

**Comment by fedarko** [comment]
for reference, this seems to be configurable by removing this line:

https://github.com/biocore/empress/blob/4f6ddd3a4e03b85703f733bd75b9771ef82157b4/empress/support_files/js/empress.js#L2291-L2293

here's what this looks like on the same portion of the MP tree --

![image](https://user-images.githubusercontent.com/4177727/91108684-7b9c9e80-e62d-11ea-8ede-57f65d0f3393.png)

The main benefit is that this is nice for certain trees where the collapsed clade's area is relatively small, e.g. the MP tree in rect layout collapsed at level 1 taxonomy --

![image](https://user-images.githubusercontent.com/4177727/91108762-b4d50e80-e62d-11ea-9b18-ab38fbf18aa9.png)

![image](https://user-images.githubusercontent.com/4177727/91108738-a2f36b80-e62d-11ea-850d-9dffe31c30db.png)

notice the small red clade containing the only Archaea-classified features in the tree. In the first screenshot it's still visible (it's just really tiny), but in the second screenshot coloring the root branch red makes (like normal) makes it a lot more visible.

**Comment by ElDeveloper** [comment]
Thanks for putting this together @fedarko, this makes a lot of sense. Thinking about it the collapsing shouldn't change the coloring of the branches, so we either extend the polygons to the top of the branch, or we color the branch as you suggest. I suspect leaving the branch makes for a more aesthetically pleasing representation.
