### ISSUE TITLE
Exported SVG images are flipped upside down

### ISSUE THREAD

**Issue by fedarko** [biocore/empress#334]

**Comment by fedarko** [comment]
Apparently just negating all of the y-coordinates in SVG exporting "fixes" this, producing an export with the same orientation as the original tree (from [this branch](https://github.com/fedarko/empress/tree/svg-export-fix)):

![image](https://user-images.githubusercontent.com/4177727/92835091-ae65c700-f38f-11ea-8d74-2c2ab49821d7.png)

That being said: I have no idea why this works. It might be the case that somewhere else in Empress' drawing code is flipping the tree vertically at some point, and the SVG export was actually "correct" all along ... not that it really matters, I guess, but it should be fixed soon at least ¯\\_(ツ)_/¯

**Comment by ElDeveloper** [comment]
@kwcantrell any idea why coordinates might be inverted in the SVG export but not in the rendering?
