### ISSUE TITLE
Don't draw node circles by default for large trees?

### ISSUE THREAD

**Issue by fedarko** [biocore/empress#349]
At least on the EMP tree I was working with, toggling node circles took a noticeable amount of time (a few seconds IIRC). If this time is presumably being used on startup to draw node circles, I think we should save that time so that the initial loading period is as short as possible -- allowing users to draw node circles later, of course.

Not sure what a good threshold would be; maybe 100k tips? (We could also just disable node circles by default; IDK what would be ideal.)

**Comment by ElDeveloper** [comment]
What about turning them off by default?

**Comment by fedarko** [comment]
Sounds good to me :) An added benefit of that is that, since node circles don't scale with zoom level, they can "overwhelm" the tree when it's zoomed out:

![nc](https://user-images.githubusercontent.com/4177727/91766050-cae35180-eb8e-11ea-89da-197737b5cab2.png)
![c](https://user-images.githubusercontent.com/4177727/91766052-cd45ab80-eb8e-11ea-94ad-9e3471e2794d.png)

**Comment by ElDeveloper** [comment]
👍 those trees look great BTW!
