### ISSUE TITLE
Root lengths in the unrooted layout?

### ISSUE THREAD

**Issue by fedarko** [biocore/empress#374]
Following up on a point raised in #363.

There is some code in the unrooted layout that accesses the length of the root node:

https://github.com/biocore/empress/blob/5d19f0dfd244b95d1ff60f3dc9a197db2bbe66c0/empress/support_files/js/layouts-util.js#L470-L478

As far as I can tell, the root node's length is actually used in the layout: if you replace `tree.length(n)` with `1000` on this line for the moving pictures dataset, the unrooted layout looks like:

![rooot](https://user-images.githubusercontent.com/4177727/92527627-268b8b80-f1dc-11ea-9872-7dceadf3b94e.png)

We currently do not do any sort of validation (in [`validate_tree()`](https://github.com/biocore/empress/blob/5d19f0dfd244b95d1ff60f3dc9a197db2bbe66c0/empress/tree.py#L16)) that the root node's length is valid (e.g. the length is specified and is a nonnegative number). Even in the moving pictures dataset, the root length is unspecified, so it looks like it defaults to 0:

![image](https://user-images.githubusercontent.com/4177727/92530501-54270380-f1e1-11ea-863e-ff1876dd23e8.png)

I think it would be best to just ignore the root branch length in the unrooted layout (and maybe just set it to 0 or something), but I am not sure what you all think.

One of the reasons for bringing this up is that as of last week Empress' UI says the following:

![image](https://user-images.githubusercontent.com/4177727/92530691-b4b64080-f1e1-11ea-8794-9a9ec2054372.png)

...so we should try to be precise about when / if the root length is used :)

**Comment by wasade** [comment]
The edge associated with a node in the BP or `TreeNode` model is from that node to its parent. The root by definition does not have a parent. If a length value is associated with the root, it should be ignored.

**Comment by fedarko** [comment]
Cool, thanks. It sounds like just setting the root length to `0` in the python code, and adjusting the unrooted layout to always keep the root length as 0 (even if "ignore lengths" is set to true), would be the way to go here.
