### ISSUE TITLE
Support "flipping" continuous color maps

### ISSUE THREAD

**Issue by fedarko** [biocore/empress#418]
So that e.g. viridis could go from yellow to purple rather than purple to yellow. This would add some more variety to the color options present in Empress.

The changes here would mostly involve the Colorer.js module within Empress, as well as some additional changes to the HTML to involve adding a UI element (checkbox?) that allows users to toggle whether or not the color map is reversed. I _think_ this might be as simple as changing `[min, max]` to `[max, min]` within this block of code:

https://github.com/biocore/empress/blob/a76ebf27a8c3730c60a8c5721aa899f2d3ff2e13/empress/support_files/js/colorer.js#L200-L206

This seems to be how the Chroma.js docs recommend doing this, at least -- see the section around [here](https://gka.github.io/chroma.js/#scale-nodata), right around where it says "To reverse the colors ..."

For reference: brought up by @kwcantrell this morning. We talked about reversing color maps in the context of Qurro a while back at https://github.com/biocore/qurro/issues/277, but I haven't got around to doing that yet :(

**Comment by gwarmstrong** [comment]
Can I grab this one?

**Comment by kwcantrell** [comment]
thanks @gwarmstrong! This will a nice feature to have.

**Comment by fedarko** [comment]
(Closed by #423.)
