### ISSUE TITLE
Internal node colouring / labelling?

### ISSUE THREAD

**Issue by gavinmdouglas** [biocore/empress#441]
Hi there,

EMPress seems like a really useful tool! Sorry if I missed this, but is there a way to colour (or otherwise label) internal nodes in a tree? I see that all tips downstream of a node could be coloured, but I would be interested specifically in indicating specific nodes somehow.

Thanks,

Gavin

**Comment by kwcantrell** [comment]
Thanks for the question @gavinmdouglas.

Currently, we support coloring internal nodes using metadata. You can create a metadata file listing the internal nodes you would be interested in coloring and then use the 'Feature Metadata Coloring' tab to color those nodes by unchecking the 'Only use tip-level metadata?' checkbox.

We are working on a method of making this processes more streamlined. But in the meantime, I can help walk you through this process.

Kalen

**Comment by gavinmdouglas** [comment]
Thanks for the rapid reply @kwcantrell, that's good to know. I'll try to figure it out myself but I may touch base with more specific questions in a few days.

All the best,

Gavin
