### ISSUE TITLE
Travis CI not getting triggered

### ISSUE THREAD

**Issue by gwarmstrong** [biocore/empress#457]
It looks like CI is not get triggered for new PR's. Based on visiting the [travis-ci page for empress](https://travis-ci.com/github/biocore/empress), it looks like we have run out of our monthly CI hours.

I believe this has not been an issue previously, but travis-ci changed their pricing rules on 11/02 so that free hours for open source software is limited: https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing

I guess one work-around is that individuals may have enough hours on their own accounts to verify based on that? E.g. https://travis-ci.com/github/gwarmstrong/empress shows my builds, including an open PR.

Otherwise, I believe GitHub Actions are free, so maybe we could transition to CI via GitHub actions? Here is a page with an example CI yaml for GitHub actions https://github.blog/2019-08-08-github-actions-now-supports-ci-cd/ 
It looks like it would not require an excessive amount of re-working the existing `.travis.yml`?

**Comment by gibsramen** [comment]
Can we consider this addressed via #465 & #468?

**Comment by fedarko** [comment]
Yeah, I think we can close this -- thanks for bringing it up.
