### ISSUE TITLE
Can Empress._to_dict be made public?

### ISSUE THREAD

**Issue by gwarmstrong** [biocore/empress#470]
The `empress.core.Empress._to_dict` method is really handy for serializing an empress object, and we would like to do this on https://github.com/biocore/microsetta-public-api/ .

As noted by @wasade on https://github.com/biocore/microsetta-public-api/pull/84 it is not great to call a private method. Is there any reason this method should not be used as, or made into a public method of the `core.Empress` object?

**Comment by kwcantrell** [comment]
I don't see any issue with making Empress._to_dict() public. The original purpose of the empress python object was to create the html page so there was no need to expose the Empress._to_dict() function as using it would be outside the scope of the object. However, it might be better to create a wrapper function for it as Empress._to_dict() returns a dict which contains references to internal variables. So before we return the dict, we would want to duplicated the objects first.

**Comment by ElDeveloper** [comment]
+1, this is a good idea and there shouldn't be any issues with that.

**Comment by gwarmstrong** [comment]
> So before we return the dict, we would want to duplicated the objects first.

Maybe something like a `copy=True`

**Comment by fedarko** [comment]
Looks like #472 addressed this, so I think we can close this (pls yell at me if not)
