### ISSUE TITLE
Write out README image links explicitly

### ISSUE THREAD

**Issue by fedarko** [biocore/empress#477]
Some of the images in the README are referred to with their full URL, as follows:

![image](https://user-images.githubusercontent.com/4177727/106341831-8a7a2380-6253-11eb-9565-6655e3bb5e8c.png)

And some of the images in the README are referred to with partial URLs:

![image](https://user-images.githubusercontent.com/4177727/106341852-99f96c80-6253-11eb-90b6-b4d8d0e68195.png)

Both of these work ok for the README on GitHub (GitHub can interpret partial URLs like the second example here), but the PyPI version of the README can't interpret these "partial" URLs. So this results in some broken images:

![image](https://user-images.githubusercontent.com/4177727/106341923-cdd49200-6253-11eb-94f1-ba63a550b430.png)

To fix this, we'd just need to adjust all image links in the README to use the full URL (as in the first example above).

Thanks @ElDeveloper for bringing this up.

**Comment by 96RadhikaJadhav** [comment]
@fedarko Can I work on the issue?

**Comment by ElDeveloper** [comment]
Thanks @96RadhikaJadhav, I've assigned you to this issue.

**Comment by fedarko** [comment]
Addressed in #478.
