### ISSUE TITLE
Explicitly test standalone installation / tests in the CI

### ISSUE THREAD

**Issue by fedarko** [biocore/empress#496]
One of the reasons that the bug in #495 slipped through, I think, is that the CI runs all of its tests within a QIIME 2 conda environment -- so if there are installation errors made due to installing Empress into an environment that _doesn't_ have all the QIIME 2 stuff pre-loaded, these errors won't be caught on the CI.

As a quick solution, one way to fix this would be adding a chunk of code (a build? a step? I'm not sure yet...) to the GitHub actions script that creates a new "vanilla" conda environment with just Python installed, and then tests that following the installation instructions in the README (see #495 -- need to install Cython/NumPy first) installs Empress properly. To test this environment, we could just run the couple of standalone-specific tests Empress has set up -- nosetest has ways of [only running a handful of tests](https://stackoverflow.com/questions/11286688/how-do-i-specify-a-single-test-in-a-file-with-nosetests).

This would be really useful to have in -- since changes within the Python ecosystem at large can be more volatile than those within a QIIME 2 environment, this sort of setup would help keep us safe from Weird Stuff Happening (tm).

**Comment by gibsramen** [comment]
I *think* this would make most sense as a separate GH Actions workflow. Can take a crack at this tomorrow.

**Comment by gibsramen** [comment]
Currently in `tests/python/test_cli.py` we're set up to load the `qza` files through the Artifact API and convert them using transformers. What do we think about changing this to just unzip the files into the the Click isolated filesystem (which we are using anyway) and removing the `qiime2` import?

https://github.com/biocore/empress/blob/26aa6ac1ec709173c5a8d00509333fc05bc31a6c/tests/python/test_cli.py#L37-L49
