### ISSUE TITLE
Get Tree Tip Label by Rectangular Layout 

### ISSUE THREAD

**Issue by neptuneyt** [biocore/empress#501]

**Comment by fedarko** [comment]
Hi @neptuneyt,

Sorry, I don't understand what you mean by this issue. Could you please clarify? Thank you!

**Comment by neptuneyt** [comment]
Dear empress team,
Thanks for your such amazing work.
Sorry about for uncompleted issue yesterday just for unreasonable netwok break.
My question is how to get the retangular layout tip label by the order of empress plot, example,.
the retangular layout tree plot tip label is 'A B D C', and I want the tip lable list 'A B D C' as that orders.
Thanks a lot!

**Comment by fedarko** [comment]
Closing in favor of #503; please re-open this if I've misunderstood.
