### ISSUE TITLE
McHelper is failing to connect

### ISSUE THREAD

**Issue by kwcantrell** [biocore/empress#517]

**Comment by ElDeveloper** [comment]
Is this because of the IPs? Or is the reason unknown?

**Comment by fedarko** [comment]
I don't think the reason is known. Looking at [the latest McHelper build that failed](https://github.com/biocore/empress/runs/2681216690) (at least on the master branch), it looks like the error message was

```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (7) Failed to connect to mchelper.ucsd.edu port 8888: Connection refused
Error: Process completed with exit code 7.
```

Not sure what's going on here.

**Comment by fedarko** [comment]
It looks like McHelper now accepts QZVs from PR branch(es), but not from master branches. McHelper worked fine for the #538 PR, but after merging this PR into master we now [get the following error](https://github.com/biocore/empress/runs/3147582588?check_suite_focus=true):

```
curl: (28) Failed to connect to mchelper.ucsd.edu port 8888: Connection timed out
Error: Process completed with exit code 28.
```

Not sure what exactly is going wrong here.

**Comment by ElDeveloper** [comment]
As best as I can tell this is working in the master branch https://github.com/biocore/empress/runs/3147708934 Closing for now. 🧙
