### ISSUE TITLE
Standalone raises incorrect parameter error 

### ISSUE THREAD

**Issue by ericap258** [biocore/empress#520]
@gibsramen 

Hi empress team, 

When using the standalone version, a wrong error message occurs.
i.e.
I tried to run the following, but got an error message indicating that I was missing the --p-filter-missing-features flag. 
!empress community-plot \
    --tree tree.nwk \
    --table 61337_reference-hit.biom \
    --sample-metadata 1070_20170412-111709.txt \
    --output-dir community-tree-viz3

Error message: File "/opt/miniconda3/envs/qiime2-2020.11/lib/python3.6/site-packages/empress/tools.py", line 247, in match_inputs
    "The feature table contains features that aren't present as "
empress.tools.DataMatchingError: The feature table contains features that aren't present as tips in the tree. You can override this error by using the --p-filter-missing-features flag.

The message should reflect the difference between standalone and qiime 2. 

I'd like to try fix this issue if that's possible. Thank you.

**Comment by kwcantrell** [comment]
Thanks @ericap258! Let me know if you have any questions!
