### ISSUE TITLE
Use a more specific class name than 'control' in Empress' CSS

### ISSUE THREAD

**Issue by fedarko** [biocore/empress#540]
> [...] would you be open to changing the name of this class to be `empress-control` or something that namespaces the class a bit better? Seems to me that `control` is too generic and prone to a collision with other CSS files.

_Originally posted by @ElDeveloper in https://github.com/biocore/empress/pull/514#discussion_r679293258_

**Comment by 1Harshini** [comment]
I would like to work on this issue.

**Comment by ElDeveloper** [comment]
Thanks for offering! We’ll be happy to review the pull request.

Yoshiki Vázquez-Baeza
