### ISSUE TITLE
Trying to install using the comand in the instructions but get always the same error

### ISSUE THREAD

**Issue by cortegas** [biocore/empress#549]
Hi everyone,

I am trying to install the plunging but the following error keeps showing up:

1 error generated.
    error: command 'x86_64-apple-darwin13.4.0-clang' failed with exit status 1

Any recommendation will be more than welcome! Thanks a lot.

**Comment by fedarko** [comment]
From looking at the original error you posted, it seems like something went wrong with the installation of the Python [`iow`](https://pypi.org/project/iow/) library (which EMPress uses to store the tree in Python) into your QIIME 2 environment. In particular, it seems like something is going wrong with Cython. These sorts of system errors can be tricky to sort out. @wasade, have you seen this error pop up before / do you have any wisdom on dealing with it? :)

For reference, I just installed a fresh QIIME 2 2021.8 environment on my system (running Linux) and was able to successfully install EMPress into the environment. So this is likely a system-specific problem.

@cortegas, could you please indicate the following things:

- How did you install QIIME 2? (And which version of QIIME 2 did you install? It looks like 2021.8, but I'd like to check.)
  - The reason I ask: I know that using the wrong [YML file for installing QIIME 2](https://docs.qiime2.org/2021.8/install/native/#install-qiime-2-within-a-conda-environment), e.g. using the linux file when you're working on macOS or vice versa, can lead to strange error messages.
  
- What specific OS version are you using? (It looks like macOS / OS X, but would be useful to know the exact version.)
  - [This link](https://support.apple.com/en-us/HT201260) should help with figuring out the version number for macOS.

- Have you tried any other QIIME 2 plugins (e.g. `qiime taxa barplot`) in this QIIME 2 conda environment; if so, do these other plugins seem to work successfully?

Thanks! Hopefully we can get this resolved. In the worst-case scenario, [installing QIIME 2 into a virtual machine](https://docs.qiime2.org/2021.8/install/virtual/) and then installing EMPress into that environment should fix this problem, but ideally we can resolve this problem without having to do that!

**Comment by cortegas** [comment]
Hi @fedarko,

- How did you install QIIME 2? (And which version of QIIME 2 did you install? It looks like 2021.8, but I'd like to check.)
**I installed qiime2 following instructions from the documents on the qiime2 website. The qiime version is 2021.8**

What specific OS version are you using? (It looks like macOS / OS X, but it would be helpful to know the exact version.)
**MacOS 11.6 version**

Have you tried any other QIIME 2 plugins (e.g. qiime taxa barplot) in this QIIME 2 conda environment; if so, do these other plugins seem to work successfully?
**The qiime taxa barplot plugging is already installed in the 2021.8 version, so I do not need to install it. But works perfectly. I have been running qiime2, and it works; it's just that I want to visualize the phylogeny tree. But, I am running into some issues installing other plugins from the qiime2 library. The metadata is downloaded correctly, but it keeps running into errors when solving the environment.**  
This is the error for the picrust plugging:
xcrun: error: unable to load libxcrun (dlopen(/Library/Developer/CommandLineTools/usr/lib/libxcrun.dylib, 0x0005): could not use '/Library/Developer/CommandLineTools/usr/lib/libxcrun.dylib' because it is not a compatible arch).
xcrun: error: unable to load libxcrun (dlopen(/Library/Developer/CommandLineTools/usr/lib/libxcrun.dylib, 0x0005): could not use '/Library/Developer/CommandLineTools/usr/lib/libxcrun.dylib' because it is not a compatible arch).

I tried to google it this second error, and according to the results, is related to the command line tools? I never run into these problems in my old mac. Weird. this is helpful to understand why I am not able to install EMpress?

Thanks for the help!

**Comment by fedarko** [comment]
Thanks @cortegas! This is very useful information.

I discussed this with @wasade, the resident Cython / iow wizard, and it seems like these sorts of problems may be caused by your Mac system not having Xcode installed. (This would especially explain the second error you mentioned, with the picrust plugin -- it looks like not having Xcode has been [documented as causing this sort of problem](https://stackoverflow.com/questions/66064033/unable-to-run-git-on-mac-os-big-sur).) Would it be possible for you to try installing Xcode (e.g. through the [app store](https://apps.apple.com/us/app/xcode/id497799835?mt=12)), and then attempt the EMPress installation afterwards?

**Comment by cortegas** [comment]
@fedarko I was wondering that since in google, that's what keeps appearing. A similar error popped up when I activated qiime, still allows me to run it and do some of the analysis until I want to install pluggings. 

Wow, Mac is forcing you now to download their apps to code, LOL. 

Thanks a lot! I will keep you posted. 
Download the xcode and see if I can run everything for future mac users.

**Comment by cortegas** [comment]
Problem solved @fedarko 

I downloaded xcode and now I am able to install the plugins with no errors. 

Thanks!

**Comment by fedarko** [comment]
Awesome, thanks for reporting back @cortegas! It's good to know that installing Xcode fixes this problem. And thanks @wasade for the help!
