### ISSUE TITLE
McHelper QZV links don't load on q2view (expired certificate?)

### ISSUE THREAD

**Issue by fedarko** [biocore/empress#560]
I noticed that, when clicking on the `view` links for the QZVs in the README, I get the following error message from q2view (in both Firefox and Chromium):

![image](https://user-images.githubusercontent.com/4177727/184302330-012e88e4-fec2-429b-9578-67d0754a5357.png)

However, these files are still hosted on McHelper. If I type in the exact URL of one of these QZVs, I instead get a warning about an expired certificate:

![image](https://user-images.githubusercontent.com/4177727/184302023-32c11f29-c4a7-4c32-a2f3-080ade4df1f9.png)

Opening up the URL anyway lets me download the QZV, and -- once this is done -- the QZV can be loaded in q2view without any visible problems. However, this seems to only be specific to the current browser (e.g. after walking through this process on Chromium, Firefox still gave me the same q2view error and then certificate expiration warning; also, this is why the screenshots above are from different browsers).

It's not a huge issue, but it would be nice to address this. One workaround would just be moving these QZVs to EMPress' GitHub repository, and hard-coding the q2view links to point to these (static) QZVs.

**Comment by antgonza** [comment]
Thank you for reporting; the certificate has been updated; could you confirm?

**Comment by fedarko** [comment]
Thank you, @antgonza! I can confirm that the links now work perfectly.
