### ISSUE TITLE
Toy viewer

### ISSUE THREAD

**Issue by mortonjt** [biocore/empress#7]
Need to create a simple view model that

1. Accepts edge metadata `pd.DataFrame`
2. Accepts node metadata `pd.DataFrame`
3. Plots the results onto a canvas using matplotlib

**Comment by YimengYang** [comment]
For now, it only plots the nodes and edges without any attribute like color. We might need to discuss the data format of attributes?

**Comment by mortonjt** [comment]
For plotting colors, sizes, ..., I think it is reasonable to have those specified as a separate column.

So for instance, if you had a method named, `color_nodes` - that could be specified as follows

```python
def color_nodes(node_metadata, color_column='Disease_Type', ...):
   """
   Parameters
   ------------
   node_metadata : pd.DataFrame
      Contains the metadata + attributes, where the row names are the node ids
      and the column names are the attributes to be plotted
   color_column : pd.DataFrame
      The column that specifies the colors for each node
   ...
   """
   ...
```
Of course, we may have another name for the view method.  But the interface should be flexible enough, where it can specify the attributes to be plotted on the fly.

With respect to designing a visualization API, I think it makes sense to follow the standards followed in [Seaborn](https://seaborn.pydata.org/examples/grouped_boxplot.html).  We can discuss API implementation details in the future.

**Comment by YimengYang** [comment]
I looked at Gneiss and is heatmap a view? Will view be an object?
