### ISSUE TITLE
Visualization rendering exploration

### ISSUE THREAD

**Issue by mortonjt** [biocore/empress#9]
Depends on #7 

Need to build a simple renderer that

1. Plots lines with attributes such as width, color and transparency
2. Plots nodes with attributes such as size, color and transparency
3. Plots polygons, (such as triangles) with specified coordinates

For starters, its worthwhile checking out these tools
- [ ] [D3](https://d3js.org/)
- [ ] [Cytoscape](http://js.cytoscape.org/)
- [ ] [Vega](https://vega.github.io/vega/) (this is extremely exploratory)
But other packages are welcome.

Worthwhile to check out JSFiddle to prototype.
An example of d3 can be found [here](https://codepen.io/ErikOdijk/pen/NGNdEx).

**Comment by kwcantrell** [comment]
We decided on WebGL
